import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Santhosh Prabhakaran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "w-full max-w-[900px] mx-auto px-4")}
      >
        {/* <ThemeProvider defaultTheme="light"> */}
        {/* <TooltipProvider delayDuration={0}> */}
        {children}
        {/* <Navbar /> */}
        {/* </TooltipProvider> */}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
